# This workflow automatically generates all manifests currently specified by the data model
# Outputs are excel files and json schemas
# Runs AFTER changes to the data model have been reviewed in a PR and merged into main

name: Store Current Manifests

on:
  push:
    branches: main
    # runs on changes to data model 
    paths: 'AD.model.jsonld'

  workflow_dispatch:

jobs:
  generate:
    name: generate-and-upload-manifests
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SCHEMATIC_SERVICE_ACCOUNT_CREDS: ${{ secrets.SCHEMATIC_SERVICE_ACCOUNT_CREDS }}
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_TOKEN_DPE }}
      SYNAPSE_UPLOAD_FOLDER_ID: syn51040197

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
          cache: 'pip'
          token: ${{ secrets.GENERATE_MANIFESTS_ON_ACTION }} # this Fine-grained PAT was generated to generate manifests despite branch protection, was granted "Read and Write access to actions" permissions, and has access to the adknowledgeportal/data-models repo (resource owner is adknowledgeportal) 

      - name: Install Libraries
        shell: bash
        run: pip install -r requirements.txt

      - name: Identify changed manifests
        working-directory: tests
        run: ./changed_manifest_selection.sh

      - name: Commit changes to tests/changed-manifests.json
        working-directory: tests
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add changed-manifests.json
          git commit -m "GitHub Action: generate JSON template with latest manifests" || echo "New version of tests/changed-manifests has been generated"
      
      - name: Generate all manifests
        working-directory: tests
        run: ./generate_test_templates.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "GitHub Action: generate latest manifests"
          title: "Update manifests"
          body: |
            This PR updates the manifests based on the latest changes.
            Please review and merge if everything looks correct.
          branch: update-manifests
          base: main
          labels: |
            automated pr
            manifest update
          reviewers: $$ {github.actor }}
          draft: false
          delete-branch: true

      - name: Upload all manifests
        working-directory: current-excel-manifests
        run: ../tests/upload_templates.sh
