name: release

on:
  push:
    tags:
      - v0.0.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.triggering_actor }}
  cancel-in-progress: true

jobs:
  release:
    if: ${{ github.triggering_actor }} != 'commit-to-main-bot-adkp[bot]' 
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_TOKEN_DPE }}
      SYNAPSE_ORGANIZATION: "sage.schemas.v2571"
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.COMMIT_BOT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_KEY }}

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          clean: false
          ref: 'refs/heads/test-main'

      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install libraries
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Register JSONSchema
        working-directory: current-manifest-schemas
        run: |
          echo "success!!"
